# Euronext Amsterdam: AEX, AMX (Midkap), AScX (SmallCap) + overige lokale noteringen
AEX = ["ADYEN.AS","AD.AS","AKZA.AS","MT.AS","ASM.AS","ASML.AS","ASRNL.AS","BESI.AS","ABN.AS",
"AGN.AS","DSFIR.AS","GLPG.AS","HEIA.AS","HEIO.AS","IMCD.AS","INGA.AS","KPN.AS","NN.AS",
"PHIA.AS","PRX.AS","RAND.AS","REN.AS","SHELL.AS","UNA.AS","WKL.AS","EXO.AS","UMG.AS"]
AMX = ["AALB.AS","ARCAD.AS","BAMNB.AS","CRBN.AS","CTPNV.AS","ECMPA.AS","FAGR.BR","FUR.AS",
"JDEP.AS","OCI.AS","PHARM.AS","SBMO.AS","LIGHT.AS","TWEKA.AS","VPK.AS","WHA.AS","AF.PA",
"BFIT.AS","CMCOM.AS","AMG.AS","APAM.AS","ALFEN.AS","INPST.AS","TKWY.AS","VVY.AS","NSI.AS"]
ASCX = ["ACOMO.AS","AJAX.AS","AVTX.AS","BSGR.AS","EBUS.AS","HEIJM.AS","HYDRA.AS","KENDR.AS",
"NEDAP.AS","ONWRD.AS","PNL.AS","SIFG.AS","SLIGR.AS","TOM2.AS","VASTN.AS","VLK.AS",
"NEWAY.AS","BRNL.AS","AXS.AS","CABKA.AS","ENVI.AS","HOLCO.AS","PORF.AS","RENEWI.AS","TITAN.AS"]
OVERIG = ["ROOD.AS","BOKA.AS","FLOW.AS","HAL.AS","KA.AS","TIE.AS","BEVER.AS","DGB.AS","NEDSE.AS",
"ORDI.AS","PSH.AS","AND.AS","ESP.AS","MKTBK.AS","GROHF.AS","ALX.AS","SGM.AS","VAST.AS"]
ALL = sorted(set(AEX+AMX+ASCX+OVERIG))
